### ISSUE TITLE
Can't start with npm run dev.

### ISSUE THREAD

**Issue by emptyhere** [m2sd/nuxt-laravel-starter#2]
vagrant@homestead:~/samosbor$ npm run dev

> @ dev /home/vagrant/samosbor
> npm run mix:dev && npm run nuxt:dev

> @ mix:dev /home/vagrant/samosbor
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

sh: 1: cross-env: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @ mix:dev: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @ mix:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-06-21T12_26_19_577Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run mix:dev && npm run nuxt:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-06-21T12_26_19_591Z-debug.log

vagrant@homestead:~/samosbor$ cat /home/vagrant/.npm/_logs/2020-06-21T12_26_19_591Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/vagrant/samosbor/node_modules/.bin:/home/vagrant/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle @~dev: CWD: /home/vagrant/samosbor
10 silly lifecycle @~dev: Args: [ '-c', 'npm run mix:dev && npm run nuxt:dev' ]
11 silly lifecycle @~dev: Returned: code: 1  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `npm run mix:dev && npm run nuxt:dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid @
15 verbose cwd /home/vagrant/samosbor
16 verbose Linux 5.4.0-37-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v14.4.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev: `npm run mix:dev && npm run nuxt:dev`
22 error Exit status 1
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Homestead, vagrant, virtualbox - last version.

**Comment by emptyhere** [comment]
5275 warn nuxt-laravel@4.2.7 requires a peer of @nuxtjs/proxy@^1.3.3 but none is installed. You must install peer dependencies yourself.
5276 warn tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
5277 verbose stack RangeError: Maximum call stack size exceeded
5277 verbose stack     at RegExp.test (<anonymous>)
5277 verbose stack     at isDepOptional (/usr/lib/node_modules/npm/lib/install/deps.js:432:45)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:441:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5277 verbose stack     at failedDependency (/usr/lib/node_modules/npm/lib/install/deps.js:457:9)
5278 verbose cwd /home/vagrant/samosbor
5279 verbose Linux 5.4.0-37-generic
5280 verbose argv "/usr/bin/node" "/usr/bin/npm" "i"
5281 verbose node v14.4.0
5282 verbose npm  v6.14.5
5283 error Maximum call stack size exceeded
5284 verbose exit [ 1, true ]

I am trying install nuxtjs/proxy & typescript, but get same error.

**Comment by emptyhere** [comment]
Solved it by `npm install` locally and `npm run dev` in vagrant.
